Repository ing-bank/lion, pull requests merged in 2019-07, with the labels that each got.

#153 Observe <html lang> attribute
  packages/localize/src/LocalizeManager.js
  packages/localize/src/localize.js
  packages/localize/test/LocalizeManager.test.js
  packages/localize/test/localize.test.js
Labels: bug

#157 [button] Fix redispatching of click event
  packages/button/src/LionButton.js
  packages/button/test/lion-button.test.js
Labels: bug

#164 Support fallback locale
  packages/localize/src/LocalizeManager.js
  packages/localize/src/localize.js
  packages/localize/test/LocalizeManager.test.js
  packages/localize/test/localize.test.js
Labels: bug, enhancement

#180 [input] Delegate "step" attribute
  packages/input/src/LionInput.js
  packages/input/test/lion-input.test.js
Labels: bug

#198 [textarea] Disable user resize behavior
  packages/textarea/src/LionTextarea.js
  packages/textarea/test/lion-textarea.test.js
Labels: bug

#204 feat(button): reduce to minimal css; use DisabledWithTabIndexMixin
  packages/button/package.json
  packages/button/src/LionButton.js
  packages/core/index.js
  packages/core/src/DisabledMixin.js
  packages/core/src/DisabledWithTabIndexMixin.js
  packages/core/test/DisabledMixin.test.js
  packages/core/test/DisabledWithTabIndexMixin.test.js
Labels: enhancement

#208 [button] Fix IE11 bugs or bugs introduced by fixes for IE11
  packages/button/src/LionButton.js
  packages/button/stories/index.stories.js
  packages/button/test/lion-button.test.js
  packages/popup/test/lion-popup.test.js
Labels: bug
